server:
  port: 8080

spring:
  profile: main
  profiles.include: 'secrets' # clientIDなどはこちらに記載する
  security.oauth2.client.registration:
    facebook:
      clientId: XXXXXXXXXXXXXXXXXXXXXX # application-secrets.ymlで上書きする
      clientSecret: XXXXXXXXXXXXXXXXXXXXXX # application-secrets.ymlで上書きする
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      resource:
        userInfoUri: https://graph.facebook.com/me
      scope: # facebookはopenid connectをサポートしてないのでscopeにopenidを指定できない
        - email
    google:
      clientId: XXXXXXXXXXXXXXXXXXXXXX # application-secrets.ymlで上書きする
      clientSecret: XXXXXXXXXXXXXXXXXXXXXX # application-secrets.ymlで上書きする
      scope:
        - openid
        - profile
        - email
  thymeleaf.cache: false
