server:
  port: 8080

spring:
  profiles.include: 'main'
  datasource:
    url: jdbc:mysql://192.168.33.10:33306/todo
    username: root
    password: rootuser
    driverClassName: com.mysql.cj.jdbc.Driver

# If you wanna enable logging for springSecurity
# https://stackoverflow.com/questions/30855252/how-do-i-enable-logging-for-spring-security
#logging:
#  level:
#    org:
#      springframework:
#        security: debug
