server:
  port: 8080

spring:
  profiles.include: 'secrets' # clientIDなどはこちらに記載する
  security.oauth2.client.registration:
    facebook:
      clientId: XXXXXXXXXXXXXXXXXXXXXX
      clientSecret: XXXXXXXXXXXXXXXXXXXXXX
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      resource:
        userInfoUri: https://graph.facebook.com/me
    google:
      clientId: XXXXXXXXXXXXXXXXXXXXXX
      clientSecret: XXXXXXXXXXXXXXXXXXXXXX
  thymeleaf.cache: false
